/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'patil' at '6/10/17 8:03 PM' with Gradle 3.0
 *
 * @author patil, @date 6/10/17 8:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
